### ISSUE TITLE
No source provided for cross compilation toolchain

### ISSUE THREAD

**Issue by b-** [droboports/docker-cross-compiler#4]
The Dockerfile downloads a prebuilt copy of the cross compilation toolchain from `ftp://updates.drobo.com/droboapps/development/SDK-2.1.zip` but I cannot seem to find the source code for that anywhere. How can I build the build environment from scratch?

**Comment by ricardopadilha** [comment]
Sorry, I get that toolchain from Drobo as is. I tried to replicate it on my own but I never quite managed to get the same thing.

_Gentle reminder: DroboPorts is not affiliated in any way with Drobo, Inc. This site is the repository of my own adventures in packaging apps for Drobo NAS devices._
